# -*- coding: utf-8 -*-
"""8_puzzle_astar_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yMASU1HRz2zT4UR2eugVOgFyxKajSvq

# 8 Puzzle A* Algorithm – Logic Explanation

## Logic of the Code

1. The puzzle is represented as a list of 9 elements.
2. The blank tile is represented by 0.
3. A* algorithm is used to find the shortest path to goal state.
4. Cost function:
   f(n) = g(n) + h(n)
   where:
   g(n) = depth (number of moves so far)
   h(n) = Manhattan distance heuristic
5. Open list is a priority queue.
6. Closed list stores visited states.
7. The algorithm continues until the goal state is reached.
8. Then the solution path is printed from start to goal.
"""

import heapq
from termcolor import colored

# Class to represent the state of the 8-puzzle
class PuzzleState:
    def __init__(self, board, parent, move, depth, cost):
        self.board = board  # Current board configuration
        self.parent = parent  # Parent state (used to reconstruct path)
        self.move = move  # Move taken to reach this state
        self.depth = depth  # Depth level in search tree (g(n))
        self.cost = cost  # Total cost f(n) = g(n) + h(n)

    # This function is required for priority queue comparison
    def __lt__(self, other):
        return self.cost < other.cost

# Function to display the board nicely
def print_board(board):
    print("+---+---+---+")
    for row in range(0, 9, 3):
        row_visual = "|"
        for tile in board[row:row + 3]:
            if tile == 0:  # Blank tile
                row_visual += f" {colored(' ', 'cyan')} |"
            else:
                row_visual += f" {colored(str(tile), 'yellow')} |"
        print(row_visual)
        print("+---+---+---+")

# Goal state configuration
goal_state = [1, 2, 3, 4, 5, 6, 7, 8, 0]

# Possible moves of blank tile
moves = {
    'U': -3,  # Move up
    'D': 3,   # Move down
    'L': -1,  # Move left
    'R': 1    # Move right
}

# Heuristic function (Manhattan Distance)
def heuristic(board):
    distance = 0
    for i in range(9):
        if board[i] != 0:
            x1, y1 = divmod(i, 3)  # Current position
            x2, y2 = divmod(board[i] - 1, 3)  # Goal position
            distance += abs(x1 - x2) + abs(y1 - y2)
    return distance

# Function to move tile
def move_tile(board, move, blank_pos):
    new_board = board[:]
    new_blank_pos = blank_pos + moves[move]
    new_board[blank_pos], new_board[new_blank_pos] = new_board[new_blank_pos], new_board[blank_pos]
    return new_board

# A* Search Algorithm
def a_star(start_state):
    open_list = []  # Priority queue
    closed_list = set()  # Visited states

    # Push initial state
    heapq.heappush(open_list, PuzzleState(start_state, None, None, 0, heuristic(start_state)))

    while open_list:
        current_state = heapq.heappop(open_list)

        # Goal check
        if current_state.board == goal_state:
            return current_state

        closed_list.add(tuple(current_state.board))

        blank_pos = current_state.board.index(0)

        for move in moves:
            # Check invalid moves
            if move == 'U' and blank_pos < 3:
                continue
            if move == 'D' and blank_pos > 5:
                continue
            if move == 'L' and blank_pos % 3 == 0:
                continue
            if move == 'R' and blank_pos % 3 == 2:
                continue

            new_board = move_tile(current_state.board, move, blank_pos)

            if tuple(new_board) in closed_list:
                continue

            new_state = PuzzleState(
                new_board,
                current_state,
                move,
                current_state.depth + 1,
                current_state.depth + 1 + heuristic(new_board)
            )

            heapq.heappush(open_list, new_state)

    return None

# Function to print solution path
def print_solution(solution):
    path = []
    current = solution

    while current:
        path.append(current)
        current = current.parent

    path.reverse()

    for step in path:
        print(f"Move: {step.move}")
        print_board(step.board)

# Initial puzzle state
initial_state = [1, 2, 3, 4, 0, 5, 6, 7, 8]

# Run A* algorithm
solution = a_star(initial_state)

# Print result
if solution:
    print(colored("Solution found:", "green"))
    print_solution(solution)
else:
    print(colored("No solution exists.", "red"))